name: DEVIN
version: 0.1.0
main: io.xchris6041x.devin.Devin
<<<<<<< Upstream, based on origin/master
author: xChris6041x
=======
load: STARTUP
>>>>>>> 9e424a7 Changed the load property from POSTWORLD to STARTUP.
